FROM node:20

WORKDIR /apps

COPY core/package*.json core/
COPY core/tsconfig.json core/

COPY notification-service/package*.json notification-service/
COPY notification-service/tsconfig.json notification-service/

WORKDIR /apps/core
RUN npm install

WORKDIR /apps/notification-service
RUN npm install

COPY notification-service/prisma ./prisma
RUN npx prisma generate

WORKDIR /apps
COPY core/src core/src
COPY notification-service/src notification-service/src

WORKDIR /apps/core
RUN npm run build

WORKDIR /apps/notification-service

EXPOSE 3002

CMD [ "npm", "run", "dev" ]
